services:
  kafka-streamflow:
    image: bitnami/kafka:latest
    hostname: kafka-streamflow
    container_name: kafka-streamflow
    volumes:
      - ./kafka:/bitnami/data
    user: root
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-streamflow:9092
      - KAFKA_BROKER_ID=1
      - KAFKA_KRAFT_CLUSTER_ID=LelM2dIFQkiUFvXCEcqRWA
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-streamflow:9093
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CREATE_TOPICS=twitter-stream:1:1
    healthcheck:
      test: ["CMD", "sh", "-c", "unset JMX_PORT; /opt/bitnami/kafka/bin/kafka-topics.sh --bootstrap-server kafka-streamflow:9092 --list"]
      interval: 10s
      timeout: 10s
      retries: 5

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    environment:
      discovery.type: single-node
      xpack.security.enabled: false
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    ports:
      - 9200:9200
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health"]
      interval: 10s
      timeout: 10s
      retries: 5

  streamflow:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      kafka-streamflow:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka-streamflow:9092
      ELASTICSEARCH_HOST: http://elasticsearch:9200
    command: ["python", "main.py"]
    volumes:
      - .:/streamflow
    ports:
      - "4000:80"
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"